kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.rabbitmq.appName }}-{{ .Values.protes.appName }}
spec:
  selector:
    app: {{ .Values.rabbitmq.appName }}-{{ .Values.protes.appName }}
  ports:
  - port: 5672
    targetPort: 5672
