# Default values for protes_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationDomain: 2.rahtiapp.fi

flower:
  appName: prowes-flower
  basicAuth: admin:admin
  image: endocode/flower

prowes:
  appName: prowes
  image: elixircloud/prowes:latest

celeryWorker:
  appName: celery-worker-{{ .Values.prowes.appName }}
  image: elixircloud/prowes:latest

mongodb:
  appName: mongodb
  databaseAdminPassword: adminpasswd
  databaseName: prowes-db
  databasePassword: prowes-db-passwd
  databaseUser: prowes-user
  volumeSize: 1Gi
  image: centos/mongodb-36-centos7

rabbitmq:
  appName: rabbitmq
  volumeSize: 1Gi
  image: rabbitmq:3-management
