apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celeryWorker.appName }}-{{ .Values.wes.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.celeryWorker.appName }}-{{ .Values.wes.appName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.celeryWorker.appName }}-{{ .Values.wes.appName }}
    spec:
      initContainers:
      - name: vol-init
        image: busybox
        command: [ 'mkdir' ]
        args: [ '-p', '/data/db', '/data/output', '/data/tmp' ]
        volumeMounts:
        - mountPath: /data
          name: wes-volume
      containers:
      - name: celery-worker-{{ .Values.wes.appName }}
        image: {{ .Values.celeryWorker.image }}
        imagePullPolicy: Always
        workingDir: '/app/cwl_wes'
        command: [ 'celery' ]
        args: [ '-A', 'worker', 'worker', '-E', '--loglevel=info', '-c', '1', '-Q', 'celery' ]
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: RABBIT_HOST
          value: {{ .Values.rabbitmq.appName }}-{{ .Values.wes.appName }}
        - name: RABBIT_PORT
          value: "5672"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "8Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /data
          name: wes-volume
        {{ if ne .Values.celeryWorker.tmpVolumeSize "0Gi" }} 
        - mountPath: /tmp
          name: celery-tmp-volume
        {{ end }}
        - mountPath: /tmp/user/.netrc
          subPath: .netrc
          name: wes-netrc-secret
        - mountPath: /app/cwl_wes/config.yaml
          subPath: app_config.yaml
          name: app-config-{{ .Values.wes.appName }}
      volumes:
      - name: wes-volume
        persistentVolumeClaim:
          claimName: {{ .Values.wes.appName }}-volume
      - name: app-config-{{ .Values.wes.appName }}
        configMap:
          name: app-config-{{ .Values.wes.appName }}
      {{ if ne .Values.celeryWorker.tmpVolumeSize "0Gi" }} 
      - name: celery-tmp-volume
        persistentVolumeClaim:
          claimName: celery-tmp-volume
      {{ end }}
      - name: wes-netrc-secret
        secret:
          secretName: netrc-{{ .Values.wes.appName }}
          items:
          - key: netrc
            path: .netrc

