---
{{ if ne .Values.celeryWorker.tmpVolumeSize "0Gi" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: celery-tmp-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName:  {{ .Values.wes.storageClass }}
  resources:
    requests:
      storage: {{ .Values.celeryWorker.tmpVolumeSize }}
{{ end }}
