---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.wes.appName }}-volume
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.wes.storageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.wes.volumeSize }}

