---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.wes.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.wes.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.wes.appName }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - celery-worker-{{ .Values.wes.appName }}
            topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: vol-init
        image: busybox
        command: [ 'mkdir' ]
        args: [ '-p', '/data/db', '/data/output', '/data/tmp' ]
        volumeMounts:
        - mountPath: /data
          name: wes-volume
      containers:
      - name: wes
        image: {{ .Values.wes.image }}
        imagePullPolicy: Always
        workingDir: '/app/cwl_wes'
        command: [ 'gunicorn' ]
        args: [ '--log-level', 'debug', '-c', 'gunicorn.py', 'wsgi:app', '--reload', '--reload-extra-file', '{{ .Values.extra_config.folder }}/{{ .Values.extra_config.file }}' ]
        env:
        - name: WES_CONFIG
          value: {{ .Values.extra_config.folder }}/{{ .Values.extra_config.file }}
        - name: MONGO_HOST
          value: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.mongodb.appName }}-{{ .Values.wes.appName }}
        - name: RABBIT_HOST
          value: {{ .Values.rabbitmq.appName }}-{{ .Values.wes.appName }}
        - name: RABBIT_PORT
          value: "5672"
        livenessProbe:
          tcpSocket:
            port: wes-port
          initialDelaySeconds: 5
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ga4gh/wes/v1/service-info
            port: wes-port
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "5Gi"
            cpu: "1"
        ports:
        - containerPort: 8080
          name: wes-port
        volumeMounts:
        - mountPath: /data
          name: wes-volume
        - mountPath: /tmp/user/.netrc
          subPath: .netrc
          name: wes-netrc-secret
        - mountPath: {{ .Values.extra_config.folder}}
          name: app-config-{{ .Values.wes.appName }}
      volumes:
      - name: wes-volume
        persistentVolumeClaim:
          claimName: {{ .Values.wes.appName }}-volume

      - name: wes-netrc-secret
        secret:
          secretName: netrc
          items:
          - key: netrc
            path: .netrc
      - configMap:
          defaultMode: 420
          name: app-config-{{ .Values.wes.appName }}
        name: app-config-{{ .Values.wes.appName }}

