---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.wes.appName }}-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.wes.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wes.volumeSize }}

