apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-{{ .Values.trs_filer.appName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.volumeSize }}
status:
