apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.appName }}
  labels:
    app: {{ .Values.rabbitmq.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.appName }}
    spec:
      {{- if eq .Values.clusterType "openshift" }}
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chmod 600 /var/lib/rabbitmq/.erlang.cookie || true; chown $(id -u):$(id -g) /var/lib/rabbitmq/.erlang.cookie || true"]
          volumeMounts:
            - name: rabbitmq-volume
              mountPath: /var/lib/rabbitmq
      {{- end }}
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-volume
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: {{ .Values.rabbitmq.appName }}-volume

