---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.rabbitmq.appName }}-volume-{{ .Volumes.prowes.appName }}
spec:
  accessModes:
    - {{ .Values.storageAccessMode }}
  resources:
    requests:
      storage: {{ .Values.rabbitmq.volumeSize }}

