apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}
spec:
  ports:
    - name: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}
