kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.mongodb.appName }}-volume-{{ .Values.protes.appName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.mongodb.volumeSize }}
