apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.appName }}-{{ .Values.prowes.appName }}
  labels:
    app: {{ .Values.rabbitmq.appName }}-{{ .Values.prowes.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.appName }}-{{ .Values.prowes.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.appName }}-{{ .Values.prowes.appName }}
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-volume
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: {{ .Values.rabbitmq.appName }}-volume-{{ .Values.prowes.appName }}