---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.rabbitmq.appName }}-volume-{{ .Values.prowes.appName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.rabbitmq.volumeSize }}
