apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-{{ .Values.cloud_registry.appName }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mongodb-{{ .Values.cloud_registry.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb-{{ .Values.cloud_registry.appName }}
    spec:
      containers:
      - image: {{ .Values.mongodb.image }}
        imagePullPolicy: Always
        name: mongodb-{{ .Values.cloud_registry.appName }}
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db/
          name: mongodb-{{ .Values.cloud_registry.appName }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mongodb-{{ .Values.cloud_registry.appName }}
        persistentVolumeClaim:
          claimName: mongodb-{{ .Values.cloud_registry.appName }}
status:
