apiVersion: v1
kind: Service
metadata:
  name: mongodb-{{ .Values.cloud_registry.appName }}
  labels:
    app: mongodb-{{ .Values.cloud_registry.appName }}
spec:
  ports:
  - name: mongodb-{{ .Values.cloud_registry.appName }}
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongodb-{{ .Values.cloud_registry.appName }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
