apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celeryWorker.appName }}-{{ .Values.protes.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.celeryWorker.appName }}-{{ .Values.protes.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.celeryWorker.appName }}-{{ .Values.protes.appName }}
    spec:
      initContainers:
      - name: vol-init
        image: busybox
        command: [ 'mkdir' ]
        args: [ '-p', '/data/db', '/data/output', '/data/tmp' ]
        volumeMounts:
        - mountPath: /data
          name: protes-volume
      containers:
      - name: celery-worker-{{ .Values.protes.appName }}
        image: {{ .Values.celeryWorker.image }}
        imagePullPolicy: Always
        workingDir: '/app/pro_tes'
        command: [ 'celery' ]
        args: [ '-A', 'celery_worker', 'worker', '-E', '--loglevel=info', '-c', '1', '-Q', 'celery' ]
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}

        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.mongodb.appName }}-{{ .Values.protes.appName }}

        - name: RABBIT_HOST
          value: {{ .Values.rabbitmq.appName }}-{{ .Values.protes.appName }}
        - name: RABBIT_PORT
          value: "5672"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "8Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /data
          name: protes-volume
      volumes:
      - name: protes-volume
        persistentVolumeClaim:
          claimName: {{ .Values.protes.appName }}-volume
