{{ if eq .Values.storage "s3" }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
stringData:
  config: |
    [default]
    # Non-standard entry, parsed by TESK, not boto3
    endpoint_url={{ .Values.s3.endpoint_url }}
  credentials: |
    [default]
    aws_access_key_id={{ .Values.s3.aws_access_key_id }}
    aws_secret_access_key={{ .Values.s3.aws_secret_access_key }}
  credentials: {{ .Files.Get "s3-config/credentials" | b64enc }}
{{ end }}
