kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.flower.appName }}-{{ .Values.protes.appName }}
spec:
  selector:
    app: {{ .Values.flower.appName }}-{{ .Values.protes.appName }}
  ports:
  - port: 5555
    targetPort: 5555
