name: Release Charts

on:
  push:
    branches:
      - main
      - test-gha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - name: Add NATS Helm repo
        run: |
          helm repo add nats https://nats-io.github.io/k8s/helm/charts/ &&
          helm repo update

      - name: Helm Dependency
        run: |
          for dir in $(ls -d charts/*); do
            helm dependency build $dir;
          done

#      - name: Helm Lint
#        run: |
#          for dir in $(ls -d charts/*); do
#            helm lint $dir
#          done
          
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          skip_upload: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Copy Index 
        run: |
          test -f .cr-index/index.yaml && cp .cr-index/index.yaml .

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

    # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
